### ISSUE TITLE
FATAL error while running 'comm' example

### ISSUE THREAD

**Issue by czekster** [pnnl/tesp#23]
Downloaded 0.6.1 version.
Updated tesp_support and all other libraries (no error so far).
Tried to run the comm example.
Called tesp/Nocomm_base/run.sh script, it yielded:

----

merlin@merlin-VirtualBox: tesp/share/examples/comm/Nocomm_Base$ **sh ./run.sh**
merlin@merlin-VirtualBox: tesp/share/examples/comm/Nocomm_Base$ starting FNCS substation loop Nocomm_Base_agent_dict.json Nocomm_Base 48 WithMarket
##,tnow,tclear,ClearType,ClearQ,ClearP,BuyCount,BuyUnresp,BuyResp,SellCount,SellUnresp,SellResp,MargQ,MargFrac,LMP,RefLoad,ConSurplus,AveConSurplus,SupplierSurplus,UnrespSupplierSurplus
unit   2 off from 111600 to 154800
Nocomm_Base.glm(28): property interim is not defined in class metrics_collector_writer
Nocomm_Base.glm(26): load failed at or near 'object metri...'
**FATAL    [INIT] : shutdown after command line rejected**

---

All logs have ZERO bytes, so I don' t know what is happening.
I searched for a discussion forum before posting here, and didn't find.

**Comment by temcdrm** [comment]
It could be finding another version of GridLAB-D first.  Can you please try "which gridlabd" and "gridlabd --version"?  If it's not the right version for TESP, then we can add some instructions on how to switch between GridLAB-D versions.

**Comment by czekster** [comment]
Just did it:
merlin@merlin-VirtualBox:tesp/share/examples/comm/Nocomm_Base$ which gridlabd
/usr/local/bin/gridlabd
merlin@merlin-VirtualBox:tesp/share/examples/comm/Nocomm_Base$ gridlabd --version
GridLAB-D 4.1.0-17925 (Lugo [852ea4df:feature/1146]) 64-bit LINUX RELEASE

Should I point to another gridlabd?
Thank you for your feedback.

**Comment by czekster** [comment]
I have copied /opt/tesp/bin/gridlabd to /usr/local/bin (to make sure the latest version would be called), however, I think there's a problem with the model:

 starting FNCS substation loop Nocomm_Base_agent_dict.json Nocomm_Base 48 WithMarket
##,tnow,tclear,ClearType,ClearQ,ClearP,BuyCount,BuyUnresp,BuyResp,SellCount,SellUnresp,SellResp,MargQ,MargFrac,LMP,RefLoad,ConSurplus,AveConSurplus,SupplierSurplus,UnrespSupplierSurplus
unit   2 off from 111600 to 154800
**Nocomm_Base.glm(28): property interim is not defined in class metrics_collector_writer**
Nocomm_Base.glm(26): load failed at or near 'object metri...'
FATAL    [INIT] : shutdown after command line rejected

**Comment by temcdrm** [comment]
When property "interim" is not defined, that indicates an earlier version of GridLAB-D (or its "tape" module) was found first. There are several components to GridLAB-D, and rather than copy files, please edit your PATH and GLPATH environment variables as suggested in the new directions here: https://tesp.readthedocs.io/en/latest/Installing_Ubuntu_Link.html and copied below:

`If you have already installed GridLAB-D, EnergyPlus, ns-3 or another simulator before TESP, it may be necessary to manually adjust your PATH and GLPATH environment variables when running TESP. The TESP versions of these simulators are built with HELICS and FNCS interfaces, which are not normally included in other versions of the simulators. In GridLAB-D, you may get an error message about “module connection” not being found. With other simulators, you might see the FNCS or HELICS broker hang, waiting for a federate that’s unable to connect.`

**Comment by czekster** [comment]
export GLPATH and TESP_INSTALL to their directories (/opt/tesp/lib and /opt/tesp)
Then I tried to run the comm example (the loadshed executed just fine), it yielded (I also ran the script killboth.sh first, to check if the daemon was stopped):
```
merlin@merlin-VirtualBox:/opt/tesp/share/examples/comm/Nocomm_Base$ ERROR: simulator 'sub1' not connected
ERROR: ACK expected, got [003] die
WARNING: fncs is not initialized
unit   2 off from 111600 to 154800
starting FNCS substation loop Nocomm_Base_agent_dict.json Nocomm_Base 48 WithMarket
##,tnow,tclear,ClearType,ClearQ,ClearP,BuyCount,BuyUnresp,BuyResp,SellCount,SellUnresp,SellResp,MargQ,MargFrac,LMP,RefLoad,ConSurplus,AveConSurplus,SupplierSurplus,UnrespSupplierSurplus
Nocomm_Base.glm(28): property interim is not defined in class metrics_collector_writer
Nocomm_Base.glm(26): load failed at or near 'object metri...'
FATAL    [INIT] : shutdown after command line rejected
```
I checked the gridlabd version:
`merlin@merlin-VirtualBox:/opt/tesp/share/examples/comm/Nocomm_Base$ gridlabd --version
GridLAB-D 4.1.0-18387 (Lugo [23dac806:feature/1173:Mod]�G) 64-bit LINUX RELEASE
`
which is the latest. I also run 
```
# pip3 install tesp_support --upgrade --no-cache-dir
# pip3 install psst --upgrade
```
but it didn't work. For property problems, as we've discussed, it seems like there's a gridlabd version problem. How does it worked for loadshed but not for comm?

```

**Comment by temcdrm** [comment]
Where did you set the GLPATH and PATH?  Is it in /etc/environment or somewhere else?

**Comment by czekster** [comment]
On the current session... export command called on an XTerm, nothing in .bashrc

I have tried putting on .bashrc on ~ and restarted the XTerm then executing the comm example, and the same error occurs.

**Comment by xcosmos6** [comment]
Hi czekster, 

I have the following comments, would you please check on them:

1, It looks like you have at least 3 different versions of gridlabd: 852ea4df:feature/1146, 181a1b2a:feature/1173, and 23dac806:feature/1173. Only 23dac806:feature/1173 is the latest one. Are you able to pin point where each of these are located?

2, In your comment above, that was 15 days ago, you said you changed the run.sh file to explicitly point to the 181a1b2a:feature/1173 gridlabd. Would you please make sure that you changed it back as 181a1b2a:feature/1173 is obsolete?

3, The tesp installer automatically append ~/.bashrc file with TESP_INSTALL, GLPATH, and 3 other environment variables. Would you please double check that is true on your system? Would you also please make sure that these environment variables do point to your latest gridlabd (23dac806:feature/1173) and tesp installation?
If None of these environment variables exists, please add them to /etc/environment, then do a "source /etc/environment" with the export keyword. Or you can add them at the end of ~/.bashrc, then exit the terminal and start a new one.

4, Would you please check the installation location of tesp? It looks like you have multiple installations, one point to "tesp/", one point to "/opt/tesp/". The default position is /opt/tesp, which requires sudo to run any of the examples, and by sudoing, all the environment variables you set above will get lost as you are running the simulation as super user. You can check them by doing "echo $TESP_INSTALL" etc. In this case you will have to set these environment variables again by "source /etc/environment".
However, if you didn't install tesp to /opt or any other directory under /(root), you should be fine.

5, From the errors you posted above, it seems that the kill script didn't clean up the processes completely sometimes, that's why you saw:
`simulator 'sub1' not connected
    ERROR: ACK expected, got [003] die
    WARNING: fncs is not initialized`
I've had that problem too, even "lsof -i :5570" does not show those processes exist. What I do is to run "fncs_broker 2", if it hangs, then run the kill script again in a different terminal. That should actually kill all the zombie processes; if an error shows up like:
    `ERROR: simulator 'sub1' not connected`
that means the sub1 process just exited. Then repeat "fncs_broker 2" till it hangs and kill it by running the kill script in a different terminal.

If you've checked all of the above and they all look good to you but you still get the error, would you please let me know exactly what you've done and record all the error messages you might find? Thank you very much!

**Comment by czekster** [comment]
> Hi czekster,
> 
> I have the following comments, would you please check on them:
> 
> 1, It looks like you have at least 3 different versions of gridlabd: 852ea4df:feature/1146, 181a1b2a:feature/1173, and 23dac806:feature/1173. Only 23dac806:feature/1173 is the latest one. Are you able to pin point where each of these are located?
> 
I have searched for gridlabd and there's only two:
```
merlin@merlin-VirtualBox:~$ /opt/tesp/bin/gridlabd --version
GridLAB-D 4.1.0-18387 (Lugo [23dac806:feature/1173:Mod]�G) 64-bit LINUX RELEASE
merlin@merlin-VirtualBox:~$ /usr/local/bin/gridlabd --version
GridLAB-D 4.1.0-18374 (Lugo [181a1b2a:feature/1173:Mod]�G) 64-bit LINUX RELEASE

```
I see that the /usr/local/bin/gridlabd version is wrong. I have created a folder on /usr/local/bin/old-gld and moved all gridlab* and fncs* there.
Then I tried to run the comm example - same error.

> 2, In your comment above, that was 15 days ago, you said you changed the run.sh file to explicitly point to the 181a1b2a:feature/1173 gridlabd. Would you please make sure that you changed it back as 181a1b2a:feature/1173 is obsolete?
> 
Yes, I have uninstall previous TESP and reinstall the new one (0.6.3) - so the scripts were overwritten and the static folder came from the original installation.

> 3, The tesp installer automatically append ~/.bashrc file with TESP_INSTALL, GLPATH, and 3 other environment variables. Would you please double check that is true on your system? Would you also please make sure that these environment variables do point to your latest gridlabd (23dac806:feature/1173) and tesp installation?
> If None of these environment variables exists, please add them to /etc/environment, then do a "source /etc/environment" with the export keyword. Or you can add them at the end of ~/.bashrc, then exit the terminal and start a new one.
> 
Yes, I have checked all variables and they are at .bashrc and pointing to the right path (GLPATH=/opt/tesp/lib TESPDIR=/opt/tesp TESP_INSTALL=/opt/tesp and PATH=$GLPATH:$PATH)

> 4, Would you please check the installation location of tesp? It looks like you have multiple installations, one point to "tesp/", one point to "/opt/tesp/". The default position is /opt/tesp, which requires sudo to run any of the examples, and by sudoing, all the environment variables you set above will get lost as you are running the simulation as super user. You can check them by doing "echo $TESP_INSTALL" etc. In this case you will have to set these environment variables again by "source /etc/environment".
> However, if you didn't install tesp to /opt or any other directory under /(root), you should be fine.
> 
I have only one folder with tesp, on /opt/tesp - there is no other tesp folder in my system

> 5, From the errors you posted above, it seems that the kill script didn't clean up the processes completely sometimes, that's why you saw:
> `simulator 'sub1' not connected ERROR: ACK expected, got [003] die WARNING: fncs is not initialized`
> I've had that problem too, even "lsof -i :5570" does not show those processes exist. What I do is to run "fncs_broker 2", if it hangs, then run the kill script again in a different terminal. That should actually kill all the zombie processes; if an error shows up like:
> `ERROR: simulator 'sub1' not connected`
> that means the sub1 process just exited. Then repeat "fncs_broker 2" till it hangs and kill it by running the kill script in a different terminal.
> 
I'll try this next. For the comm case I'm seeing fncs_broker 4 in runcombined.sh so I guess I have to adjust this set also. I have tried to run each command on runcombined.sh but it doesn't work properly as well.

> If you've checked all of the above and they all look good to you but you still get the error, would you please let me know exactly what you've done and record all the error messages you might find? Thank you very much!

It looks like the wrong gridlabd is being called, I agree. I'll keep an eye on next versions as well, as I've mentioned, **the odd thing is that the loadshed example do work...**

**Comment by czekster** [comment]
Still didn't make it work again.
The same error appears: `ModuleNotFoundError: No module named '_helics'`
I have a file called /opt/tesp/python/helics.py that inside has the following code:
`if __package__ or "." in __name__:
      from . import _helics
else: 
      import _helics    # this is the line with the error`

What is wrong? My guess this is not a GridLAB-D problem, it's something else. Maybe something is not installed or updated because I have made it work 3 weeks ago... I have all the variables and tesp_updates - I checked the variables for compiling TESP from the source and I have all the variables...

Is it too much trouble to install a VM with KUbuntu, download TESP-0.6.3, set the environment variables and paths, and all dependencies and make the loadshed example work?

**Comment by temcdrm** [comment]
There was an issue last year with _helics.so under certain conditions, but that issue was closed and it was also specific to Mac OS X (https://github.com/GMLC-TDC/HELICS/issues/643).  Have you installed anything else, especially something that might have affected Python or HELICS, over the past few weeks?

We normally make separate VMs for different projects, but only with Ubuntu 18.04 LTS, to insulate from system and platform dependencies.  Is Docker an option for you?

**Comment by czekster** [comment]
I used the Docker version - all installed correctly.
Then I make and make install the ns-3 file.
All compiled on the ns-3 and copied to the right folder.

However, when running the loadshed, it takes a few seconds to 'run' (Total time: 2.0 seconds - I know this is not right, because it took me several hours last time I've managed to run). 

Should I do something in this Docker version that is not listed in the loadshed example ?

**Comment by temcdrm** [comment]
Actually, the loadshed example is small and should only take a second or two.  Did your Docker experiment produce the *metrics.json files as expected?

A successful run should not have taken several hours the last time, unless you're talking about the entire autotest script.

**Comment by czekster** [comment]
> Did your Docker experiment produce the *metrics.json files as expected?
This file was not generated.
I asked a colleague to run Docker and he came with the same results as I, where the loadshed example takes 2 seconds and nothing is printed with the `python3 plot_loadshed.py loadshed` command.
The other time that it ran I was on a VM, it took some 2 hours, but it generated the graphs from the python script.

**Comment by czekster** [comment]
PS: I'm trying to run the ./runhpy.sh (with HELICS Python and ns-3).

**Comment by temcdrm** [comment]
User was able to resolve it in a VM
