### ISSUE TITLE
Energy+ HELICS example

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#35]
In the [HELICS Energy+ run.sh](https://github.com/pnnl/tesp/blob/master/examples/energyplus/eplusHelicsExample/run.sh), it looks like the config file that is referenced should be `eplusH.json`.

**Comment by temcdrm** [comment]
This was Heng's temporary test case and it won't run without some manual tweaks.  It's not distributed with the installer or part of the autotest.  Re-assigning to Heng for either fixing it, or just removing it from the repository.

**Comment by xcosmos6** [comment]
@trevorhardy I cannot figure out where the problem is as it works fine on my end. I would suggest you to try runh.sh under the /examples/energyplus directory instead of the run.h under /examples/energyplus/eplusHelicsExample to see if you get the same problem. Those two examples are very similar except the time frame it simulates. As for run.h, it does refer to eplus.json. This eplus.json is actually exactly the same as eplusH.json under /examples/energyplus directory. And the helics_eplus_agent2.json is exactly the same as eplus_agentH.json under /examples/energyplus directory.

**Comment by trevorhardy** [comment]
Ahh, my mistake. I thought the JSON config file that needed to be used was for HELICS the one that had "helics" in the name but after looking at the file referenced in the shell script I can see that it is also a HELICS config file. Is there a reason for having two config files there?

Anyway, closing this out.
