### ISSUE TITLE
some problems when I run plot_loadshed.py

### ISSUE THREAD

**Issue by Yyz710** [pnnl/tesp#54]
I followed the Tutorial:
    cd ~/tesp/examples/loadshed
    ./clean.sh
    ./runhpy.sh
    python3 plot_loadshed.py loadshed
But the problem occured,
    File "plot_loadshed.py", line 49, in <module>
        print ("There are", len (times), "sample times beginning with", times[1] - times[0], "second intervals")
    IndexError: list index out of range

In _plot_loadshed.py_, if it has run lst_m.pop('StartTime') and meta_m = lst_m.pop('Metadata'), st_m becomes a empty dict. So, I have a defective _billing_meter_loadshed_metrics.json_? The data in the file are as follows:

{"Metadata":{"above_RangeA_Count":{"index":22,"units":""},"above_RangeA_Duration":{"index":12,"units":"s"},"above_RangeB_Count":{"index":24,"units":""},"above_RangeB_Duration":{"index":14,"units":"s"},"below_10_percent_NormVol_Count":{"index":27,"units":""},"below_10_percent_NormVol_Duration":{"index":26,"units":"s"},"below_RangeA_Count":{"index":23,"units":""},"below_RangeA_Duration":{"index":13,"units":"s"},"below_RangeB_Count":{"index":25,"units":""},"below_RangeB_Duration":{"index":15,"units":"s"},"bill":{"index":8,"units":"USD"},"reactive_energy":{"index":7,"units":"VARh"},"reactive_power_avg":{"index":5,"units":"VAR"},"reactive_power_max":{"index":4,"units":"VAR"},"reactive_power_min":{"index":3,"units":"VAR"},"real_energy":{"index":6,"units":"Wh"},"real_power_avg":{"index":2,"units":"W"},"real_power_max":{"index":1,"units":"W"},"real_power_min":{"index":0,"units":"W"},"voltage12_avg":{"index":11,"units":"V"},"voltage12_max":{"index":10,"units":"V"},"voltage12_min":{"index":9,"units":"V"},"voltage_avg":{"index":18,"units":"V"},"voltage_max":{"index":17,"units":"V"},"voltage_min":{"index":16,"units":"V"},"voltage_unbalance_avg":{"index":21,"units":"V"},"voltage_unbalance_max":{"index":20,"units":"V"},"voltage_unbalance_min":{"index":19,"units":"V"}},"StartTime":"2000-01-01 00:00:00 EST"}

**Comment by trevorhardy** [comment]
I'll look into it; hopefully today.

**Comment by trevorhardy** [comment]
Sorry, this item slipped through my to-do list and I just found it again. 

I ran the commands you provided above in TESP on a Ubuntu VM (installed using the installer) and I was able to successfully create the graphs. Which is to say I wasn't able to replicate your bug.

I looked at my billing_meter_loadshed_metrics.json and I have the metadata you have as well as lots of simulation data. You are correct, for some reason the data isn't making it into that file.

If you repeat this process but use `./run.sh` instead of `./runhpy.sh` does it work for you?
